misc(ci): version-tag eq check

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -12,7 +12,7 @@ jobs:
 
   auto-release:
     runs-on: ubuntu-latest
-    if: github.ref_type == 'tag'    
+    if: github.ref_type == 'tag'
     needs: call-check-build
     steps:
       - uses: actions/checkout@v4
@@ -37,7 +37,7 @@ jobs:
             echo "working on: '$platform'"
             cd "$platform" # NOTE: needed for tar & sha256sum
 
-            bin_path="$(ls)" # WARN: errors if more 
+            bin_path="$(ls)" # WARN: errors if more
             echo "binary found: '$bin_path'"
             tar_path="$platform.tar.gz"
             echo "tarring up..."; tar -czvf "$platform.tar.gz" "$bin_path"
@@ -54,14 +54,21 @@ jobs:
 
           ls -lARh target/release-binaries # beautiful!
 
-      - name: Draft a GitHub release
+      - name: Create a GitHub release
         uses: softprops/action-gh-release@v2
         with:
-          draft: true
+          # draft: true
           generate_release_notes: true
           files: target/release-binaries/*
           prerelease: ${{ contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc') }}
 
       - name: Publish to crates.io
-        if: "! (contains(github.ref, 'alpha') || contains(github.ref, 'beta') || contains(github.ref, 'rc'))"
-        run: cargo publish --token "${{ secrets.CRATESIO_TOKEN }}" --verbose --dry-run
+        shell: bash
+        run: |
+          version="$(grep version Cargo.toml | head -n1 | cut -d '"' -f2)"
+          git_tag="$(basename ${{ github.ref }})"
+          echo "Cargo.toml version is: '$version', github tag is: '$git_tag'"
+          if [ "$version" != "$git_tag" ]; then
+            echo "error: they don't match!"; exit 1
+          fi
+          cargo publish --token "${{ secrets.CRATESIO_TOKEN }}" --verbose
